### ISSUE TITLE
Is Slicedit a training-free method?

### ISSUE THREAD

**Issue by 1851759** [fallenshock/Slicedit#2]
I'm excited for your excellent work. I see there is no training code.Is Slicedit a training-free method ? Or could you please release training code and datasets?

**Comment by fallenshock** [comment]
Hi, thanks for taking interest in our work :)
Exactly, Slicedit is a training-free method, fully leveraging the 2D prior of Stable Diffusion in both the spatial and spatio-temporal video axes.
